# vqgan_ckpt: 'AutoencoderModel.ckpt'
vqgan_ckpt: '/home/data/yanghao/DiffTumor-main/DiffTumor-main/last.ckpt'

# Have to be derived from VQ-GAN Latent space dimensions
diffusion_img_size: 24
diffusion_depth_size: 24
diffusion_num_channels: 17
out_dim: 8
dim_mults: [1,2,4,8]
results_folder: checkpoints/ddpm/
results_folder_postfix: 'fold0_tumor_early_96_t4'
load_milestone: False

batch_size: 2 # 40
num_workers: 20
logger: wandb
objective: pred_x0
save_and_sample_every: 1000
denoising_fn: Unet3D
train_lr: 1e-4
timesteps: 4 # number of steps
sampling_timesteps: 250 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
loss_type: l1 # L1 or L2
train_num_steps: 60000 # total training steps
gradient_accumulate_every: 2 # gradient accumulation steps
ema_decay: 0.995 # exponential moving average decay
amp: False # turn on mixed precision
num_sample_rows: 1
gpus: 0


seed: 1234

accumulate_grad_batches: 1
default_root_dir: checkpoints/vq_gan/
default_root_dir_postfix: '8k_96_d4_steplr'
resume: False
resume_version: 0
resume_from_checkpoint: ~
pretrained_checkpoint: ~
max_steps: 80000
max_epochs: -1
precision: 16
gradient_clip_val: 1.0

embedding_dim: 8
n_codes: 16384
n_hiddens: 16
lr: 3e-4
downsample: [4, 4, 4]
disc_channels: 64
disc_layers: 3
discriminator_iter_start: 10000
disc_loss_type: hinge
image_gan_weight: 1.0
video_gan_weight: 1.0
l1_weight: 4.0
gan_feat_weight: 4.0
perceptual_weight: 4.0 
i3d_feat: False
restart_thres: 1.0
no_random_restart: False
norm_type: group
padding_type: replicate
num_groups: 32

